In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings(action = 'ignore')
%matplotlib inline

# 스케일링
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Data Loading

In [2]:
# 데이터 불러오기
target = pd.read_csv('cust_train.csv', encoding = 'UTF-8')
numeric_f = pd.read_csv('numeric_features.csv', encoding = 'UTF-8')
sparse_f = pd.read_csv('sparse_pca.csv', encoding = 'UTF-8')

In [3]:
# numeric과 sparse feautre merge 후 CLNT_ID 제거
features = pd.merge(numeric_f, sparse_f, on = 'CLNT_ID', how = 'left')
del features['CLNT_ID']
col_name = list(features.columns)
features

,amount_sum,buy_num,amount_mean,amount_max,amount_min,amount_std,amount_cv,visit_act_div,most_visit_act_cnt,female_brand_amount_sum,...,503,504,505,506,507,508,509,510,511,512
0,86500,2,43250.000000,81000,5500,53386.561980,0.872832,1,2,0.0,...,0.090386,0.048184,0.102888,0.015704,-0.010796,0.003406,0.001622,0.059246,0.065646,0.034018
1,1276000,16,79750.000000,99000,39000,22944.861444,0.278574,6,6,0.0,...,-0.003204,0.356164,0.017675,-0.247674,0.143313,-0.088780,-0.470668,0.089675,-0.491101,0.338045
2,560000,11,50909.090909,62100,20000,13065.255799,0.244696,2,10,0.0,...,0.231761,-0.241417,-0.378696,0.064967,-0.166866,-0.372142,0.370277,-0.493969,0.367671,0.423290
3,851200,8,106400.000000,110400,102400,4276.179871,0.037594,2,4,0.0,...,0.289376,-1.640709,-0.513414,-0.403203,-0.192333,0.839212,0.011350,-0.026235,0.306186,-0.951131
4,125200,6,20866.666667,37000,12800,12496.826264,0.546709,2,4,0.0,...,-0.229937,0.278148,0.172552,-0.013737,0.143273,0.092610,-0.419746,-0.122221,0.010405,0.359551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375859,80000,3,26666.666667,35000,20000,7637.626158,0.233854,2,2,0.0,...,0.035172,0.061968,-0.056762,-0.043489,-0.037338,0.071399,-0.179281,0.022034,-0.103932,-0.003625
375860,902800,12,75233.333333,149000,35400,38881.248889,0.494807,9,2,902800.0,...,-0.132898,0.140498,0.014950,0.075242,0.213181,0.098828,0.243707,-0.173046,0.006346,0.406067
375861,91800,2,45900.000000,45900,45900,0.000000,0.000000,1,2,0.0,...,-0.132762,0.212653,0.276099,0.045414,-0.098765,0.203992,0.074390,0.358834,0.042201,-0.108899
375862,92000,4,23000.000000,23000,23000,0.000000,0.000000,1,4,0.0,...,-0.152633,0.023162,-0.027840,0.100499,-0.079910,0.148920,0.039644,0.087765,0.020548,-0.068979
375863,69900,1,69900.000000,69900,69900,0.000000,0.000000,1,1,0.0,...,-0.022443,-0.015088,0.067570,-0.026996,0.002415,-0.010604,0.059937,0.066826,0.025754,0.029001

# Feature Scaling

In [ ]:
# 이상치 제거
features = features.apply(lambda x: x.clip(x.quantile(.05), x.quantile(.95)), axis=0)
features

In [ ]:
# Scaler 선언
mms = MinMaxScaler()
ss = StandardScaler()

# Scaling
features = mms.fit_transform(features)
features = ss.fit_transform(features)

# 다시 dataframe 형태로 바꾸기
features = pd.DataFrame(features, columns = [str(i) for i in col_name])
display(features)

# train과 test feature 분리하기
train_features = features.iloc[:263104,:]
test_features = features.iloc[263104:,:]

display(train_features, test_features)

# Feature Save

In [23]:
train_features.to_csv('train_features.csv', encoding = 'UTF-8', index = False)
test_features.to_csv('test_features.csv', encoding = 'UTF-8', index = False)