## Base Data 전처리

In [8]:
import numpy as np
import pandas as pd

base_data = pd.read_excel('seoul_apart.xlsx').iloc[:,:9]
base_data

                    단지  준공년도    전용면적  계약년도    계약일   거래금액  층  자치구  법정동
0       개포6차우성아파트1동~8동  1987   54.98  2010   1.28  66000  3  강남구  개포동
1                  NaN   NaN   67.28  2010   8.25  80000  4  강남구  개포동
2                  NaN   NaN          2010  12.28  67000  4  강남구  개포동
3                  NaN   NaN   79.97  2010   8.05  80600  5  강남구  개포동
4                  NaN   NaN          2010   9.02  83000  1  강남구  개포동
...                ...   ...     ...   ...    ...    ... ..  ...  ...
744603             NaN   NaN   84.34  2020    2.2  32000  3  중랑구  중화동
744604         한영(103)  2003   61.36  2020   5.05  23000  2  중랑구  중화동
744605         한영(104)  2003   66.24  2020   2.03  28500  5  중랑구  중화동
744606             NaN   NaN   70.96  2020   1.28  31200  4  중랑구  중화동
744607             NaN   NaN  106.21  2020   3.11  45400  6  중랑구  중화동

[744608 rows x 9 columns]

In [9]:
base_data['전용면적'] = base_data.전용면적.apply(lambda x: np.nan if x == ' ' else x)
base_data.ffill(axis = 0, inplace = True)
base_data = base_data.drop_duplicates()
base_data.to_csv('base_data.csv',index = False)
base_data

                    단지  준공년도    전용면적  계약년도    계약일   거래금액  층  자치구  법정동
0       개포6차우성아파트1동~8동  1987   54.98  2010   1.28  66000  3  강남구  개포동
1       개포6차우성아파트1동~8동  1987   67.28  2010   8.25  80000  4  강남구  개포동
2       개포6차우성아파트1동~8동  1987   67.28  2010  12.28  67000  4  강남구  개포동
3       개포6차우성아파트1동~8동  1987   79.97  2010   8.05  80600  5  강남구  개포동
4       개포6차우성아파트1동~8동  1987   79.97  2010   9.02  83000  1  강남구  개포동
...                ...   ...     ...   ...    ...    ... ..  ...  ...
744603         한영(102)  2003   84.34  2020    2.2  32000  3  중랑구  중화동
744604         한영(103)  2003   61.36  2020   5.05  23000  2  중랑구  중화동
744605         한영(104)  2003   66.24  2020   2.03  28500  5  중랑구  중화동
744606         한영(104)  2003   70.96  2020   1.28  31200  4  중랑구  중화동
744607         한영(104)  2003  106.21  2020   3.11  45400  6  중랑구  중화동

[740598 rows x 9 columns]

In [7]:
base_data.단지.nunique()

7264

In [11]:
import numpy as np
import pandas as pd
base_data = pd.read_csv('base_data.csv')

C:\Users\Lee_HyeonJun\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (1,2,3,4,5,6) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [15]:
base_data[:100]

                단지  준공년도   전용면적  계약년도    계약일   거래금액  층  자치구  법정동
0   개포6차우성아파트1동~8동  1987  54.98  2010   1.28  66000  3  강남구  개포동
1   개포6차우성아파트1동~8동  1987  67.28  2010   8.25  80000  4  강남구  개포동
2   개포6차우성아파트1동~8동  1987  67.28  2010  12.28  67000  4  강남구  개포동
3   개포6차우성아파트1동~8동  1987  79.97  2010   8.05  80600  5  강남구  개포동
4   개포6차우성아파트1동~8동  1987  79.97  2010   9.02  83000  1  강남구  개포동
..             ...   ...    ...   ...    ...    ... ..  ...  ...
95        개포주공 1단지  1982  42.55  2010  11.12  79200  3  강남구  개포동
96        개포주공 1단지  1982  42.55  2010  11.18  80400  4  강남구  개포동
97        개포주공 1단지  1982  42.55  2010  12.07  79500  1  강남구  개포동
98        개포주공 1단지  1982  42.55  2010  12.09  79500  1  강남구  개포동
99        개포주공 1단지  1982  45.26  2010   3.18  81500  2  강남구  개포동

[100 rows x 9 columns]

In [16]:
base_data.자치구.nunique()

91